# Generated by Django 3.2.7 on 2021-10-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('kakao_id', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('mobile_number', models.CharField(max_length=100, null=True)),
                ('college', models.CharField(max_length=100, null=True)),
                ('introduction', models.CharField(max_length=1000, null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('duty', models.CharField(max_length=100, null=True)),
                ('salary', models.DecimalField(decimal_places=3, max_digits=15, null=True)),
                ('date_of_joining', models.DateField(null=True)),
                ('date_of_resigning', models.DateField(null=True)),
                ('in_office', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
