# Generated by Django 3.2.7 on 2021-10-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True),
        ),
    ]
