# Generated by Django 3.2.7 on 2021-10-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_file',
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_file_url',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
