# Generated by Django 3.2.7 on 2021-10-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='salary',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
