# Generated by Django 3.2.7 on 2021-10-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='black', max_length=45),
            preserve_default=False,
        ),
    ]
